### ISSUE TITLE
 An NCCL question about run.sh

### ISSUE THREAD

**Issue by ferrari700** [ICEORY/PMF#1]
Hello, I'm sorry to disturb you. I encountered NCCL problem when executing bash run.sh. It seems to be a problem with the number of GPUs. How can I solve it? Thanks!
![Screenshot from 2021-10-22 12-35-03](https://user-images.githubusercontent.com/72401926/138398350-84b23482-c167-4957-b9af-967c42161cb8.png)

**Comment by iris0329** [comment]
Hi @ferrari700 

Do you use torch 1.8.1 and python 3.6? 
What kind of GPU you are using?
