### ISSUE TITLE
 data placement structure of the dataset?

### ISSUE THREAD

**Issue by emilyemliyM** [ICEORY/PMF#10]
Dear author
 what is the data placement structure of the dataset?
such as seamantic kitti, like,  are there images and lidar data under sequence00?

**Comment by iris0329** [comment]
For convince, we use the same structure as SemanticKITTI (original 360 one)

**Comment by emilyemliyM** [comment]
> For convince, we use the same structure as SemanticKITTI (original 360 one)

Dear author, 

How can I set the "nuscenes" dataset structure like the Semantic KITTI dataset?
LIKE scene-0000 ,scene-0001, ...?
Is there any script? 

Really thanks.

**Comment by iris0329** [comment]
Hmm, it's kind of hard to set nuScenes dataset structure like the SemanticKITTI dataset, because nuScenes is based on the token to sample data.
