### ISSUE TITLE
When shall we use pcd_aug? 

### ISSUE THREAD

**Issue by hadonga** [ICEORY/PMF#11]
#### Thanks in advance for sharing your code for public research. The code is very standardized and easy to understand.
For my understanding, ./pc_processor/dataset/preprocess/augmentor.py is to preform PC augmenting operation such as flip, translation, etc. However, my concern is whether this will break image matching ( Lidar to camera2 matrix). Then I noticed that you have set the value of pcd_aug to false in ./tasks/pmf/trainer.py. 
##### 2.  In what situations should we adopt pcd_aug? 

Looking forward to your reply, thanks.

**Comment by iris0329** [comment]
Thanks for attention.
1. Use pcd augmentation in the training stage. What written in the ./tasks/pmf/trainer.py is just a default value, you can check [augmentation related config](https://github.com/ICEORY/PMF/blob/master/tasks/pmf/config_server_kitti.yaml#L38) for more info.
2. Pcd augmentation is to avoid over fitting, it's nearly always used in the training stage, but some methods will also adopt augmentation in the test stage, you can google test time augmentation or TTA for details, but I think it's more like a kaggle trick, which cannot improve the real ability of the algorithm.

**Comment by Jun-CEN** [comment]
Hi @hadonga Did you reproduce the performance reported in the paper using augmentation?

**Comment by hadonga** [comment]
Hi there. Data augmentation is a nice try to improve the performance. However, as you mentioned in your email, it turns out the performance is even worse after w/ augmentation. In my opinion, it is because the simple augmentation(augmentor.py) will break the consistency between PC and image.  You can find some cross-modal augmentation papers to get more insights. good luck~  ps. pointaugmenting is a good paper.
