### ISSUE TITLE
about experiment environment 

### ISSUE THREAD

**Issue by Towiko** [ICEORY/PMF#3]
Hello, I'm sorry to disturb you. According to the paper, I only konw about you did it under the GeForce RTX 3090. But some errors occurred when I wanted to reproduce your experiment. So could you please tell me exactly what's your experiment environment? (Something like **requirements.txt** )

**Comment by marius12233** [comment]
Hi @Towiko , 
I don't know whether my answer could help you, however I was able to run the experiment using python 3.7.4 and torch==1.7.0+cu101.

**Comment by Towiko** [comment]
thanks for your reply @marius12233,
I have finished my environment setup, but there still seem to be some problems.Now that you have successfully conducted the experiment, I would like to ask you :

1: I run the experiment but it has this error
![image](https://user-images.githubusercontent.com/65336241/146388952-781814e2-63f0-4523-be2b-70531b00d8ef.png)
I only changed the dataset root and the number of gpu, what else should i do to change the code?

2: For now i only used the semantic kitti dataset, the directory is like:
![image](https://user-images.githubusercontent.com/65336241/146389570-94263809-42bc-4535-99ce-b72f50b31da3.png)

is that right?

**Comment by songw-zju** [comment]
hi @Towiko , I met this problem before. Have you solved the problem？

**Comment by Towiko** [comment]
@songw-zju  Nope，still waiting for @marius12233 ‘s’ reply while rereading the paper. If this is not an exception I suspect there is a problem with the source code. @ICEORY

**Comment by marius12233** [comment]
Hi @Towiko. Unfortunately I ran the experiment on nuScenes, not on Kitti,, and now I'm unable to reproduce the experiment using Kitti.
However, the folder structure seems to be good, so if you can tell me which line throws the exception I will happy to help you to figure out whether it is a problem with source code or not.

**Comment by Towiko** [comment]
Thanks so much for your help@marius12233 ,here's the error messages
![image](https://user-images.githubusercontent.com/65336241/146899255-94f4f99d-bea8-4db7-8869-3a1eee6db592.png)
![image](https://user-images.githubusercontent.com/65336241/146899315-506a713f-84be-4ad2-a93f-6d05b1b0d5fe.png)
![image](https://user-images.githubusercontent.com/65336241/146899370-3c1c18bb-74f9-4377-ac46-799b951ef782.png)
![image](https://user-images.githubusercontent.com/65336241/146899424-da46bd68-1367-4d9d-a902-cd66607b6a30.png)

It seems that some errors occurred in dataloader and this [perspective_view_loader.py] file
![image](https://user-images.githubusercontent.com/65336241/146899797-c11767a2-49b1-40e8-b219-b638b4e5d77a.png)

**Comment by iris0329** [comment]
Hi @Towiko 


![image](https://user-images.githubusercontent.com/26380036/147061860-6c8f1d79-8be4-4356-a961-64d37cd0834d.png)

According to your error report, please check the image type.

**Comment by marius12233** [comment]
Hi @Towiko ,
The error was likely generated by torchvision transform module, because
your version seems to accept as input only a PIL image, and not a tensor as
well.
This is due to the pytorch version, which carries out an old version of
torchvision. Probably your version of torch is 1.1 or below, which is your
torch version?
Probably installing a newest torch and torchvision version could solve the
issue.
For example, my torch version is 1.7.1 and torchvision version is 0.8.2,
and checking in functional.py inside the transforms library it accepts both
PIL Image and Tensors.

Il giorno mer 22 dic 2021 alle ore 09:37 Iris ***@***.***> ha
scritto:

**Comment by songw-zju** [comment]
> Hi @Towiko , The error was likely generated by torchvision transform module, because your version seems to accept as input only a PIL image, and not a tensor as well. This is due to the pytorch version, which carries out an old version of torchvision. Probably your version of torch is 1.1 or below, which is your torch version? Probably installing a newest torch and torchvision version could solve the issue. For example, my torch version is 1.7.1 and torchvision version is 0.8.2, and checking in functional.py inside the transforms library it accepts both PIL Image and Tensors. @songw-zju probably you have the same problem.

Thanks for your useful advice. I reinstall torchvision for higher vision and solve the problem.
