### ISSUE TITLE
corresponding images dataset download link

### ISSUE THREAD

**Issue by emilyemliyM** [ICEORY/PMF#9]
Hello 
Dear author, I only found the lidar data of the semanti kitti dataset, can I get its corresponding images dataset download link?
or Nuscenes，...
Sorry, I really can't find it.

Thanks!

**Comment by mengshiyu0109** [comment]
http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d?

Is that link right?

**Comment by 56aaaaa** [comment]
For Nuscenes
https://www.nuscenes.org/nuscenes#code

**Comment by mengshiyu0109** [comment]
> For Nuscenes https://www.nuscenes.org/nuscenes#download

Thanks for the reply, I have found the nuscenes and Semantic kitti lidar data.

Could I have the link about the images for kitti segmentation ? 
thank!

**Comment by LiXiaoHang6** [comment]
Did you encounter this problem during the validation phase? There is no problem during the training phase, but it runs with errors during the validation phase. I'm not sure if it's a problem with the data set or the code. Can you share your data set structure, especially the image data added separately?

RuntimeError: stack expects each tensor to be equal size, but got [19961] at entry 0 and [123389] at entry 1.

**Comment by myself0816** [comment]
I only found the laser radar data from the semanti kitti dataset. Can I get the corresponding image dataset download link?

**Comment by iris0329** [comment]
@myself0816 @emilyemliyM 
Sorry for missing the question, for SemanticKITTI, please refer kitti odometry
https://www.cvlibs.net/datasets/kitti/eval_odometry.php

**Comment by myself0816** [comment]
> @myself0816 @emilyemliyM 很抱歉错过了这个问题，对于语义KITTI，请参考kitti测程 https://www.cvlibs.net/datasets/kitti/eval_odometry.php

But I didn't find the corresponding image data

**Comment by myself0816** [comment]
So the image is the 55g file with the data?

**Comment by iris0329** [comment]
Hope it helps you
Download odometry data set (color, 65 GB)

**Comment by myself0816** [comment]
so I Download odometry data set (color, 65 GB),and
[Download](http://www.cvlibs.net/download.php?file=data_odometry_velodyne.zip) KITTI Odometry Benchmark Velodyne point clouds (80 GB)
[Download](http://www.cvlibs.net/download.php?file=data_odometry_calib.zip) KITTI Odometry Benchmark calibration data (1 MB)
[Download](http://semantic-kitti.org/assets/data_odometry_labels.zip) SemanticKITTI label data (179 MB).
Finally, I can get the complete dataset that PMF needs, right?

**Comment by myself0816** [comment]
原谅我，第一次整这个，啥都不懂

**Comment by iris0329** [comment]
y

**Comment by myself0816** [comment]
> 您可以尝试一下，请

感谢您的帮助
